### ISSUE TITLE
Quest / NPC: Escape Through Force / Volcor

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#1148]
**Quest** - Escape Through Force _(ID:994)_
**NPC** - Volcor _(ID:3692)_
- **Issue (1) present:** Once you reach the destination, Volcor will not give you credit for rescuing him at all. 
- **Issue (2) present:** Volcor will not despawn and reset on the end, making him permanetly stuck in one spot until the server restarts or crashes completely.
- **How it should work:** Volcor should also give the credit on the end of the escort and he should reset properly after quest is done.

---

http://www.wowhead.com/quest=994/escape-through-force
http://www.wowwiki.com/Quest:Escape_Through_Force
http://www.wowwiki.com/Volcor

---

Related quests: #1149 - the only difference in quests is the loot, the process and method is exactly the same.
_Also, player CAN NOT do both of the quests, he can do only one._

**Comment by glitterlance** [comment]
Confirmed. The quest still appears to be bugged in the same way.

**Comment by Stihii** [comment]
Bug still reproduces (05 June 2016).

**Comment by Stihii** [comment]
I tried to kill the furbolgs around the cave in the hopes that maybe it triggers the next stage of the quest where I have to go to Auberdine and get the reward but it did nothing, Volcor despawns same as usual after walking towards the road. He despawns somewhere near Grimclaw.

**Comment by Rushor** [comment]
you do not need to push this anymore, fix will be available soon

**Comment by Stihii** [comment]
Thanks for the info.
P.S. Great job, guys, great response times and everything; I am happy to be playing on a server managed by such a pro team.

**Comment by Rushor** [comment]
```sql
UPDATE `smart_scripts` SET `target_type`=17, `target_param2`=30 WHERE `entryorguid`=369200 AND `source_type`=9 AND `id`=3 AND `link`=0;
UPDATE `smart_scripts` SET `target_type`=17, `target_param2`=30 WHERE `entryorguid`=369201 AND `source_type`=9 AND `id`=3 AND `link`=0;
UPDATE `smart_scripts` SET `event_param2`=3692 WHERE `entryorguid`=3692 AND `source_type`=0 AND `id`=2 AND `link`=0;
UPDATE `smart_scripts` SET `event_param1`=110000, `event_param2`=110000 WHERE `entryorguid`=369200 AND `source_type`=9 AND `id`=2 AND `link`=0;
UPDATE `smart_scripts` SET `event_param1`=110000, `event_param2`=110000 WHERE  `entryorguid`=369201 AND `source_type`=9 AND `id`=2 AND `link`=0;
```

**Comment by Stihii** [comment]
I don't mean to be pushy with this, but the bug is still present, I just tested it 5 minutes ago.

**Comment by Rushor** [comment]
d290279e197fe38960bca430639b2a6615c19bc4
- he will now properly give the questcredit and despawn and reset after despawn
- testable on ptr

**Comment by Golganeth** [comment]
Gives quest credit but Volcor doesn't attack any enemy, and doesn't say any quote.

**Comment by Golganeth** [comment]
Gives quest credit but Volcor doesn't attack any enemy (he tries to but instantly evades back and forth), and doesn't say any quote on start/end escort.

**Comment by Stihii** [comment]
I also re-tested on Algalon and I can confirm what Golganeth said, although Volcor kept repeating "Oh no here they come" everytime I engaged a furblog. All in all it gave the quest credit and I was able to finish it.

**Comment by Rushor** [comment]
DB/Quest: Escape Through Force + Escape Through Stealth - Rework both questevent

* Volcor will no longer try to do the "sit" emote during the escortpath
* Volcor will become hostile to the furbolgs (he can attack them now)
* updated Volcor's starttext once the quest was accepted
* closes https://github.com/dalaranwow/dalaran-wow/issues/1149
* closes https://github.com/dalaranwow/dalaran-wow/issues/1148
* commit: d290279e197fe38960bca430639b2a6615c19bc4
* commit: 31f6af1fa0ef30570d49f92e99a1baab220ccad7

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by wrathofthebug** [comment]
Hi it's been a year since this was last updated. Would just like to bring up the fact that the quest is still not working as intended. Upon initiating the escort quest Volcor just starts walking out of the cave towards Grimclaw without stopping at all. He also does not aggro all the furbolgs that are within aggro range as he walks, leading to the player having to deal with a whole group of mobs and it is literally impossible to keep up with Volcor's walking pace while fending off all the mobs or even just to stay alive till Volcor reaches Grimclaw for the player to get the quest credit.
