### ISSUE TITLE
[Hunter] Explosive Trap

### ISSUE THREAD

**Issue by wonopon** [dalaranwow/dalaran-wow#1196]
Explosive Trap (http://wotlk.openwow.com/spell=13813) does not deal any instantaneous damage to the enemy that steps on the trap; it only applies the DoT to enemies within 10 yds.

**Comment by Milton3450** [comment]
Hello! Addition. Hunters in the duelling area of Dalaran will put an explosive trap after duel has ended and you have 1 hp. It will kill you even tho the duel is finished. It doesn't even have to be the hunter you are duelling. I have seen a few hunters do it. Not giving any names (Suxface)!

**Comment by robinsch** [comment]
@Lothloryen Was this ever applied or was it removed?

**Comment by Lothloryen** [comment]
@robinsch  This was deployed, but it was not working properly - removed some time after.

**Comment by Rushor** [comment]
Game/Spells: Hunter - Explosive Trap - Add initial damage and increase DoT amount

* closes https://github.com/dalaranwow/dalaran-wow/issues/1196
* commit: 77b403daa084e7e2d793362d841f53088d9e7f48

![GitHub Logo](http://i.imgur.com/kYbGBea.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Hello after few fast tests on PTR the results are:

 - This:

> I'd like to add to this thread that explosive trap does damage in sanctuary areas (dalaran) to the opposit faction.

I wasn't able to reproduce it in Dalaran city.

 - This:

> Game/Spells: Hunter - Explosive Trap - Add initial damage and increase DoT amount

works as intended on PTR in pvp.

I wasn't able to test it in pve as the issue with the traps from report #3026 is still present on PTR. I will retest it when it is avaliable (but I will assume it's working properly as the logic for this trap should be thesame in pvp and pve.
