### ISSUE TITLE
Quest: That Which Creates Can Also Destroy - Reanimated Frost Wyrm

### ISSUE THREAD

**Issue by wamwam** [dalaranwow/dalaran-wow#1353]
For the Quest "That Which Creates Can Also Destroy" you have to kill 3 NPCs including Reanimated Frost Wyrm. The item Seeds of Nature's Wrath has to be used on a Reanimated Frost Wyrm so it becomes a Weakened Reanimated Frost Wyrm and falls down to the ground (so it can be killed). 

How it currently works: 
When you use Seeds of Nature's Wrath the Reanimated Frost Wyrm becomes a Weakened Reanimated Frost Wyrm and falls to the ground. The problem is however, it becomes stuck in the ground and can't be attacked. I've tried multiple times but it keeps happening. This makes it impossible to complete the quest.

How it should work:
The Weakened Reanimated Frost Wyrm should fall to the ground properly so it can be attacked.

Quest: http://www.wowhead.com/quest=12459/that-which-creates-can-also-destroy
Quest Item: http://www.wowhead.com/item=37887
NPC: http://www.wowhead.com/npc=26841
NPC after quest item is used: http://www.wowhead.com/npc=27821

Screenshot showing the problem: 
![image](https://f.cloud.github.com/assets/6825998/2429690/228137ba-ac92-11e3-8dce-d3ebfd51bba8.png)

Video of how it should work: http://youtu.be/NRRdiA1P2SU?t=15s

**Comment by petrozz** [comment]
Still bugged and not doable. I found 4 "weakened reanimated dragons" but they were already weakened (obviously) and untargetable.

**Comment by exiledone** [comment]
doable with a Deathknight....the reanimated wyrms on the ground will start attacking u if standing close enough. but for some reason they damage themselves also. after a few hit i could use my deathgrip on it and pull it closer or out of the ground....a few swings and the creature died. i complete the quest without too much of a hustle, and got one step closer to killin Arthas!!:)

**Comment by 1ncredebil** [comment]
Quest is DOABLE, BUT it takes effort and patience.
First you need to know, that even though some dragons visually appear to be afk chilling on the ground, they are not actually there, but rather somewhere high in the skies, unreachable from the ground. There is, however, a place where they fly lower to the ground. It's at the SOUTHWEST entrance of Galakrond's rest, where the 2 dark pillars are. There you can usually target the reanimated dragons with the quest item, and quickly pull their aggro (after they have been weakened that is). 
- If the dragon gets stuck mid-air, casting his frost spell at you, dont try walking out of range, cause you will simply lose the aggro and he will fly away. Instead, what you should do, is try hide behind the pillar. That way the dragon should be lured right next to you, where you can kill him even as a melee.
The dragons are the only difficult part about this quest. Best of luck

**Comment by Lothloryen** [comment]
Hello there, 

This quest was fixed already.

Thank you for your reports.

**Comment by Golganeth** [comment]
When weakened, the frost wyrms are on the ground (visually near the player) but they are actually out of reach.

**Comment by Lothloryen** [comment]
This should be corrected, thank you.

**Comment by ImprezaWoW** [comment]
The quest works fine, but SOMETIMES there are problems with Turgid the Vile running under the terrain when he's in the weakened state. Don't know if it's possible, and if it is, it's very low priority, but perhaps if the Weakened version of the mob is not killed in 10 minutes(or whatever short duration) of using the item, he should despawn and the normal version should spawn back? Would prevent issues like these.

**Comment by Slashkill** [comment]
On Algalon this quest is far from fixed.

First of all the dragons are so far up in the sky that due to your limited vision on this server u can't see them. Second of all the dragons still doesn't land but merely keep flying alittle bit then resetting the moment u hit them with a spell.

**Comment by TeridanDW** [comment]
Thank you for pointing out these issues @Slashkill .
The entire area of Galakrond's Rest and all creatures there will be reworked here #1413
