### ISSUE TITLE
[Outland][Alliance][Kurenai faction][Zangarmarsh]

### ISSUE THREAD

**Issue by Akkalevil** [dalaranwow/dalaran-wow#1373]
Several quests for the Kurenai gives only 250 rep, while they should give 500 rep.

http://www.wowwiki.com/Kurenai

Also, I couldn't find a link, but I'm pretty certain you don't start at 0/3000 unfriendly with Kurenai, but at 1000 or 2000 (we should be able to reach neutral rep without having to go to another zone, which is not possible at the moment, even with human diplomacy bonus).

**Comment by Augur89** [comment]
Still an issue, the last patch didn't fix this.

**Comment by Ston3y** [comment]
I can confirm it is still an issue. I'm 200 rep shy of neutral with Kurenai from doing all their (available) quests in Orebor, Zangarmarsh.

**Comment by PolarCookie** [comment]
still an issue

**Comment by Rushor** [comment]
DB/Quest: Kurenai - double quest reputation

* this does not affect the dailyquest-reputation, only the non-repeatable quests
* closes https://github.com/dalaranwow/dalaran-wow/issues/1373
* commit: 1fdb895ded61e4ef36fe26d3f6fdc74d3ee88d4c

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Works as intended on ptr.

**Comment by Radschpud** [comment]
This is still an issue. I got less than friendly in Zangarmarsch, so I couldnt proceed with the remaining quest. I had to go to Nagrand to do 1more quest to get enough reputation.
:-/
