### ISSUE TITLE
[General] Spell Range calculation (Whirlwind + Cleaveand hit boxes)

### ISSUE THREAD

**Issue by Rathyan** [dalaranwow/dalaran-wow#1386]
http://wowhead.com/spell=1680

Whirlwind has range issues with mobs with very large hit boxes. For example on Sartharion, and even the Drakes, I had to stand right on top of them for my Whirlwind to do damage to them. Even though I was standing inside the hit box on Sartharion and my Bloodthirst was in range, Whirlwind would not do damage.
I didn't notice this on Sapphiron though, maybe because I was focusing on not eating the Blizzard instead of looking at my damage output up closely

Current behaviour:
Cleaving range is not working as it is suposed to, examples of this in ToC are snowbolds, mistresses and infernals on jaraxus and anubarak ads, unless they are inside boss hitbox you wont be able to cleave them unless you are targetting the ads themselves.

Expected behaviour:

https://www.youtube.com/watch?v=1mYHEzHuld8&t=276s

This a link from a retail video where you can clearly see the warrior positioning and how his cleave will hit 3 targets even while targetting the boss.

Steps to reproduce the problem:

Get the same positioning of the ads and the warrior, try to cleave, only anubarak gets damaged by the cleave.

**Comment by Rushor** [comment]
general issue will all spell-range calculations

**Comment by Rushor** [comment]
possible fix in https://github.com/TrinityCore/TrinityCore/pull/16290 (needs updates + testing)

**Comment by chaodhib** [comment]
Yeyo. I'm the author of the potential fix. If you got a chance to test it, please let me know if it works.

Thanks.

chaodhib

**Comment by Rushor** [comment]
This is fixed with https://github.com/TrinityCore/TrinityCore/commit/a1f2f30c145f6ad9c4baeffeff32618e71ff537c. The fix will be applied with further merges on the live realm in the future. Thanks for the report.

**Comment by ashido96** [comment]
Hey @Rushor do you have any idea when the live the server is going to be getting some of these fixes, more specifically for raids. There's been some stuff you fixed with ToC 5+ months ago that we still don't see implemented. 

I know there's a ton of stuff that's been fixed and pushing it all at once to live server can cause some troubles but can you try and get in contact with @Lothloryen to try and get raid and major mechanic fixes like this to have priority when getting pushed to the live server. It's nice that fixes are happening, but "fixed on PTR" has literally become a meme in my guild whenever fixes get discussed.

Thanks for all the work you do for the server.

**Comment by Edzero** [comment]
Entirely dependant on Loth in that regard.

**Comment by Rushor** [comment]
yep see what Edzero said
