### ISSUE TITLE
[Spell] Fear pathing in arena shows a player at wrong place | Spells movement problem

### ISSUE THREAD

**Issue by chereyo** [dalaranwow/dalaran-wow#1447]
When you fear someone in arena, you'll be seeing them run around, but their actual position is different. When fear is about to end/ends, the feared character will teleport/move very fast towards another location. It obviously makes it near impossible to do any kind of followup on feared targets.

**Comment by Rushor** [comment]
please share the fix for it, and i will give you some hunter fixes from my server - let me know if you want something

**Comment by Serpentsting** [comment]
opened 6 apr 2014 
now its 27 oct 2016 and nobody fix it cool 
https://youtu.be/3lI3NzO7j4s
https://youtu.be/WTWkjia_wTI
https://youtu.be/YKQJc8Qypzk

**Comment by Edzero** [comment]
Duplicate threads are always closed. I'll ask Robinsch to work on this but I believe he's not got internet access for some time.

**Comment by Serpentsting** [comment]
WTB Scatter fix, these bug make MOST arenas unmatchable
now just we playing as dpmm vs wp i cant do !!!EVEN!!! 1 TRAP CUZ you CAN'T FIX ONE BUG 2 YEARS !!!

**Comment by Serpentsting** [comment]
how soon u fix it?
or i must comment it again in 2018?

**Comment by Serpentsting** [comment]
bump

**Comment by Serpentsting** [comment]
BUMP.

**Comment by Serpentsting** [comment]
HEY GUYS BUMP AGAIN

**Comment by Rushor** [comment]
follow the update of https://github.com/TrinityCore/TrinityCore/issues/15952 in order to see the progress

**Comment by Rushor** [comment]
Core/Spell: Fixed a bug where players would teleport after confuse or fear movement

* Issue: https://github.com/dalaranwow/dalaran-wow/issues/1447
* Ref: https://github.com/TrinityCore/TrinityCore/issues/15952
* commit: bfe1780dcfa6b5416239232bd3677622e9101838

by @robinsch 

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Works as intended on ptr.

**Comment by Serpentsting** [comment]
After 3 years LOAL best devs eva


13 жовтня 2017, 22:19:02, від Teridan <notifications@github.com>: 


Works as intended on ptr.

**Comment by KerDW** [comment]
@TeridanDW @Lothloryen This is still an issue on live, not as bad as it used to be though.

**Comment by TeridanDW** [comment]
This used to work fine for me on PTR, can someone else comfirm if this is still problematic on live.
Video will be nice.

**Comment by TeridanDW** [comment]
Regarding:

> Gonna add that this happens too with Scatter Shot and probably any other disorient effect, which makes landing traps harder.
> 
> The cause of this bug seems to be movement speed since scatter+trapping mounted targets is almost impossible due to this bug.

This is what I see on PTR:
https://www.youtube.com/watch?v=ABSpM42cRf0&feature=youtu.be
is it diffrent from live?

**Comment by Lothloryen** [comment]
Hello there, 

Applied a fix for the remaining issues, it should be fine after the next scheduled maintenance.

Thank you very much.

**Comment by Jiaku** [comment]
For love of god, please fix fear pathing, it is impossible to predict where target will end up

**Comment by Aridam** [comment]
Yeah this is still bugged. It always happens with Fears/Disorients and such pathing-related CC.

**Comment by Aridam** [comment]
Correction: This basically happens with any CC with _any_ movement involved (sometimes Charge, Death Grip often, etc.). So basically anything that CCs anyone while they are moving/and causes them to move in any fashion, causes this to happen -- just-saw it happening to Death Grip.

**Comment by Aridam** [comment]
Bump.

This is still bugged -- be it Fear, Death Coil, someone using Charge or Intercept or Feral Charge, it doesn't matter, because it's all the same. Sometimes it gets so bad and in such moments where the last thing you need is to have exactly this happening, that it's just unplayable.

**Comment by Aridam** [comment]
Second bump.

This visual bug has practical effects as well. For example a Warrior Charges and I'm where they were when they cast it. My client shows I can't use Throw but can use Melee Abilities, however, I actually can't -- because of this, I actually can use neither Throw because of false feedback, nor Melee attacks because of, again, false feedback.
