### ISSUE TITLE
[NPC][Outland] Boulderfist Ogres

### ISSUE THREAD

**Issue by Akkalevil** [dalaranwow/dalaran-wow#1581]
The Boulderfirst Mages and Boulderfist Warriors don't use their abilities (no spellcasting, no charge, etc.) and just run to you and mêlée you.

**Comment by Rushor** [comment]
npc ids for this?

**Comment by Rushor** [comment]
DB/Creature: Add abilities for Boulderfist Mage and Boulderfist Warrior

* Boulderfist Warrior - On Aggro - Cast 'Shoulder Charge'
* Boulderfist Mage - In Combat - Cast 'Frostbolt'
* Boulderfist Mage - Between 0-30% Health - Cast 'Bloodlust'
* Boulderfist Mage - In Combat - Cast 'Fire Blast'
* closes https://github.com/dalaranwow/dalaran-wow/issues/1581
* commit: 461aba39bee6910cfa0e0f53c9a8935f5cc6a3ac

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Aridam** [comment]
Confirming this as it seems that nearly a year after the last post here, the Boulderfist Mages are still not using any of their Abilities at the moment.
