### ISSUE TITLE
[Event] Kalu'ak Fishing Derby Broken

### ISSUE THREAD

**Issue by cypherrage** [dalaranwow/dalaran-wow#1648]
As a precursor, the Elder is supposed to do a Northrend wide announcement when the contest starts but he doesn't.

Myself and 2 friends fished the entire hour of the contest and did not catch the shark at all.  I fished for about 20 minutes non-stop in pools in Dragonblight, then I moved to the river in Sholazar Basin for the remainder of the event (non-pool fishing). My first friend was in Howling Fjord fishing from pools the entire time, and the last was just fishing in the river in Crystalsong Forest.

Is there any confirmation on whether or not this event works properly?

**Comment by Augur89** [comment]
I spent the entire event duration fishing on The Frozen Sea (Borean Tundra) to no avail for two weeks in a row. If the event is broken and the Blacktip Shark doesn't drop no matter what it's alright, but I'd like some confirmation from the development team to stop wasting my time every week...

Thanks!

**Comment by Reechter** [comment]
Confirmed broken as of 23.01.2016. Fishing schools in Sholazar for 40 minutes I caught 162 Suckerfish and no shark. May be related to #1689.

**Comment by datbunneh** [comment]
Any information?

**Comment by Rushor** [comment]
Scripts/World: Implement Kalu'ak Fishing Derby

* add Blacktip Shark to northrend schools
* add worldannouncements to Elder Clearwater
* 13: 55 he will yell: The Kalu\'ak Fishing Derby starts in 5 minutes!
* 14:00 he will yell: The Kalu\'ak Fishing Derby has begun! The first person to bring a blacktip shark to me in Dalaran will be declared the winner! Blacktip sharks can be caught anywhere you can catch a pygmy suckerfish.
* If someone won the event, he will yell: $N has won the Kalu\'ak Fishing Derby!
* 15:00 he will yell: The Kalu\'ak Fishing Derby has ended! If you caught a shark, please bring it to me within the hour.
* closes https://github.com/dalaranwow/dalaran-wow/issues/1648
* commit: 00a9aeae963f7941fe6650a80e2a00e33dabd5ed

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by galgnu** [comment]
Could this please be testet - should be quit straight forward ;-)

**Comment by galgnu** [comment]
Would love to see this live!

**Comment by Rahizm** [comment]
As of April 28th, it's still not working. NPC is there, but sharks aren't spawning. Fished in Sholazar and Grizzly Hills, caught almost 4 stacks of pygmy fish, but no sharks.

**Comment by FruitShopOwner** [comment]
Seems to be broken again - 

I've tried to do it 4 times in multiple locations: Unu'pe and the Frozen Sea in Borean Tundra, Valgarde in Howling Fjord, the river west of Amberpine Lodge in Grizzly Hills, River's Heart in Sholazar Basin, and a bit at Lake Kum'uya again in Borean Tundra

I would mention that my character is level 10, but I'm pretty sure the event has no level limit, since I can interact with Elder Clearwater to see that the quest is available to me, among other reasons

The first time I did it, I believe a winner was announced, but never again, even though I've encountered other people fishing from schools during the event

**Comment by Lothloryen** [comment]
Should be fine now.
