### ISSUE TITLE
[Spell] Pain Suppression and Hand of Freedom 

### ISSUE THREAD

**Issue by pascagabriel** [dalaranwow/dalaran-wow#1690]
Pain supression seems to be castable while polimorphed (http://youtu.be/xTjyqti3ngs?t=5m53s). This seems to be because the priest is still stunned (glyph) while casting Pain Supression even though he is already sheeped.

**Comment by Crispybuilt** [comment]
Pentex and me just tested this on PTR and it appears the report is correct.

**Case 1:** 
- *Use Hammer of Justice on a enemy target*
- *Use Polymorph while the Stun is still active*
- *Target is able to cast Pain Supression regardless the polymorph*

**Case 2:**
- *Use Polymorph first on a enemy target*
- *Use Hammer of Justice while Polymorph is up*
- *Target is **not** able to cast Pain Supression

Obviously, the case 1 has to be fixed since in both scenarios buffs are overlapping.

**Comment by Rushor** [comment]
this was updated by:

Core/Spell: revamp of immunities system

- Spell attributes research
- Container optimization
- Do not skip damage immunity checks on SPELL_ATTR0_UNAFFECTED_BY_INVULNERABILITY present
- Added additonal arguments support to SendCastResult / CheckCast, spells can now send proper error messages
- Loads spell immune masks/states/effects at startup.
- This cached info is used whenever a spell cast requires immunities to be known beforehand (to see if an aura could be applied for example)

* commit: 3506bd5e039a141133087e92af128c390615f573
* commit: 654739dc421236cdd1815746ce8cd1ba3cfb4236
* commit: 815294ed120ba7e8946fbf026df6553babd75354

Please recheck on ptr if the issue is still present. ty.

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
After fast test on ptr, case 1 mentioned above:

> Case 1:
> 
> Use Hammer of Justice on a enemy target
> Use Polymorph while the Stun is still active
> Target is able to cast Pain Supression regardless the polymorph

Is still happening so reopening the issue.

**Comment by TeridanDW** [comment]
Works as intended on PTR.
