### ISSUE TITLE
[NPC] Charles Worth - Tailoring pattern for Wispcloak and Deathchill cloak

### ISSUE THREAD

**Issue by Millamagia** [dalaranwow/dalaran-wow#1848]
Hello!

Achievements for those two cloak patterns are vice versa in Algalon realm. 
I did the achievement "Loremaster of Northrend" to get the Deathchill cloak pattern from Charles Worth, the tailoring trainer in Dalaran (how it should work). So when i finally got the achievement, the trainer, Charles, actually gave me pattern for Wispcloak that should require "Northrend Dungeonmaster" achievement. 

After that he had a talk option about deathchill cloak where Charles would tell something like "Only the one with Loremaster of Northrend achievement is worth of learning the secrets of this cloak blah blah..." At this point _i did not have_ dungeon master achievement. When i finally got the dungeonmaster achievement Charles teached me how to sew Deathchill cloak.

I dont have any screenshots ect. about this, sorry.
Here are links to npc's, items ect.

http://www.wowhead.com/npc=28699/charles-worth ///Grand master tailoring trainer in Dalaran.
http://www.wowhead.com/item=41610 ///Deathchill cloak
http://www.wowhead.com/item=41609 ///Wispcloak
http://www.wowhead.com/achievement=1288 ///Dungeonmaster ach.
http://www.wowhead.com/achievement=41 ///Loremaster ach.

Next text is taken from wowwiki:
Achievement cloaks
Upon reaching 420, tailors unlock two cloak recipes that can be learned from the Dalaran trainer once the proper achievements have been completed. (Note that this information appears in the trainer's gossip text window, rather than the normal training screen.) To learn the [Deathchill Cloak], players must complete the Money achievement Loremaster of Northrend achievement, which requires you to complete the majority of quests in every Northrend zone. The [Wispcloak] requires the achievement Money achievement Northrend Dungeonmaster, which requires you to complete every 5-man dungeon in Northrend. Both cloaks are Bind on Equip and can be sold.

This could be major bug for some players because getting Loremaster of Northrend isnt that easy job to achieve due to so many bugged quests/chains, and the reward for that is not what it should be.

-Millamagia, Algalon

**Comment by Rushor** [comment]
DB/Creature: Assign gossips of Charles Worth to the correct achievements and profession skills

* closes https://github.com/dalaranwow/dalaran-wow/issues/1848
* commit: e0c9d2f8e1f0bb5712da9a4b88b43bf20b1fdb7c

![GitHub Logo](http://i.imgur.com/i3FzGHJ.jpg)
![GitHub Logo](http://i.imgur.com/95uFvzn.jpg)
![GitHub Logo](http://i.imgur.com/0TqLep2.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by ErasmusHereticus** [comment]
Issue has not been resolved yet. 

Wispcloak remains unobtainable after attaining the Dungeonmaster achievement.

**Comment by Sfmsk** [comment]
Still not resolved. Got the Northrend Dungeonmaster achievement today and was rewarded with the Deathchill Cloak recipe.
