### ISSUE TITLE
[Quest][Northrend] Shoot 'Em Up

### ISSUE THREAD

**Issue by Balathor** [dalaranwow/dalaran-wow#1898]
For the quest Shoot 'Em Up in Icecrown currently the cannons you have to use to shoot down the drakes riders are not usable. I've tried clicking them and using hotkeys to mount to no avail.

de.wowhead.com/quest=13069

According to other players they become usable after a server reset but once used go dormant.

**Comment by taralej90** [comment]
I can't even use the harpoons x)

**Comment by Camarila** [comment]
Still bugged and the harpoons are not usable...

**Comment by shilofax** [comment]
Still bugged. Harpoons are usable now, however there are no drakes spawned.

**Comment by Augur89** [comment]
This quest is doable but it takes a very long time and the protodrakes spawn in pairs at most. And I think the harpoons have to be fixed in place, now when you "mount" one you can move...

So yeah it's doable but annoying.

**Comment by DrFuler** [comment]
[07/04/2016] - Seems to be very bugged. Can't kill the dragons because they just fly away...

**Comment by DrFuler** [comment]
[09/04/2016] - Quite painful, but doable.

**Comment by Rushor** [comment]
todo:
- add usablableflag in creature_template
- remove speed
- reduce respawntime

**Comment by budthechud** [comment]
As of today the harpoons are usable but when the drakes/riders are hit they do not take damage.
Attached is a screenshot of my combat log after shooting several drakes/riders point-blank.
http://i.imgur.com/SadBMRy.jpg
Notice their is no information about the damage being or not being dealt to the targets.

**Comment by Rushor** [comment]
do you were able to see the dragons sometimes?

**Comment by budthechud** [comment]
I was able to see a few dragons, about 4, then nothing.  I fired at the ones I saw and nothing came up in the log, scrolling text, or anything.

**Comment by Rushor** [comment]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Description**:

While handling the Jotunheim Rapid-Fire Harpoon there are 2 bugs encountered : 

1) You can use Energy Reserve to always have full energy. It does not have the 30 sec cooldown it should have that is mention in the skill description.
2) The Rapid-Fire Harpoon deals no dmg or it's bugged or the Proto-Drake are out of vision even tho they appear to be in sights.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)

 This quest is bugged and can't be finished due to the fact that the Proto-Drake's can't be shot down.

**Expected behaviour**: Tell us what should happen instead

1) You should only be able to use Energy Reserver once every 30 sec.
2) The continous dmg from the Rapid-Fire Harpoon should kill the Proto-Drakes.

**Steps to reproduce the problem**:

1.  Take the quest.
2.  Try to shoot down Proto-Drakes.
3.  Use/spam Energy Reserve.

**Include proofs for this behaviour**

https://postimg.org/gallery/fu3keyfq/
http://wotlk.openwow.com/quest=13069
http://www.wowhead.com/quest=13069/shoot-em-up
https://www.youtube.com/watch?v=CC1-RJ_TsI0
http://wowwiki.wikia.com/wiki/Quest:Shoot_'Em_Up

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by MrAndersonX** [comment]
Thanks.

**Comment by Rushor** [comment]
DB/Quest: Shoot 'Em Up - Set the drakes active and reduce respawntime

* closes https://github.com/dalaranwow/dalaran-wow/issues/1898
* commit: a8a2efce7dc6985f40faf625d7dbdb28e7f29c56
* Energy Reserve now has a cooldown of 30 seconds
* the drakes are active now which means that they are more visisble (we cannot do more to fix that)
* the drakes will respawn after 60 seconds, the quest is easier doable now
* Rapid-Fire Harpoon only targets the drakes now (no longer selfkill)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

@MrAndersonX fixed - would you like to bumb some more nasty northrend quests that needs to be fixed? :P

**Comment by MrAndersonX** [comment]
@Rushor Thanks alot mate :P ! And sure, as soon as I have the time to play some more it's not a problem :). Will also go for Loremaster at one point or another and then I'll update all the bugs I encounter (in the very distant future tho).

**Comment by ScarletPoem** [comment]
The Quest Still doesnt work, the harpoons are usable but dont do any damage to that 1 drake that keeps floating around, making the quest unfinishable.
