### ISSUE TITLE
Paladin Sanctified Retribution

### ISSUE THREAD

**Issue by Snusnufs** [dalaranwow/dalaran-wow#2559]
Hello.

I have noticed that Sanctified Retribution (http://wotlk.openwow.com/spell=31869) only gives the 3% damage increase when used with Retribution aura. It wont give the 3% damage when used with any of the other auras.

**Comment by Nikvet** [comment]
Confirmed,Yes.

**Comment by Golganeth** [comment]
Same exact issue @strobe-light described regarding Swift Retribution. Few ways to reproduce easily (same applies for Swift Retribution - #1711)

1)
- Apply the talent while having Retribution Aura on yourself. (%dmg will be there)
- Now change to any other Aura (%dmg is gone will only work with Retribution Aura)

--------

2)
- Apply the talent while having no auras or any aura that isn't Retribution on yourself.
- You can now see the %dmg with any aura, as long as you don't use Retribution Aura (in which case it will break for all auras once again)

----------

3) 
- Be on a spec where you don't have Sanctified Retribution and change to one where you do.
- When the spec change happens, if you dont have any aura on yourself or one that isn't Retribution, it will work for as long as you don't use Retribution Aura.


IMPORTANT: When making specs to test this, avoid  'Crusade' talent which also increases damage by 3% and could lead to confusion.

**Comment by robinsch** [comment]
All issues should be fixed.

**Comment by Golganeth** [comment]
If there's two or more paladins in the same group/raid, both with the sanctified/swift retribution talents, there's one scenario where the bonus damage/haste can glitch out:

- First paladin uses an aura
- Second paladin uses another aura
- First paladin removes his aura
- Bonus damage/haste are gone even though second aura is up. 
(this won't happen if the second paladin is using Retribution Aura, will happen with any other)

It's a not very likely scenario but happens. There's also a small visual bug in your character sheet when changing between auras, it will go 100% for like half a second then back to 103% (both dmg and haste)

(Minor issues, can have low priority)

**Comment by robinsch** [comment]
Updated

**Comment by Golganeth** [comment]
The visual issue is gone. However the following issue still remains:
Two paladins in raid/group: both %dmg and %haste will be gone if the first paladin who used the aura with talents removes his aura. This will not happen if the second paladin with the talents was using Retribution Aura.
Very unlikely scenario that can be solved pretty easily by refreshing - reapplying the aura. 

Can have very low priority.

**Comment by Lothloryen** [comment]
My bad, I did not applied properly to the PTR, it should be now.

**Comment by Golganeth** [comment]
Fixed, works like a charm now.

**Comment by Golganeth** [comment]
Edit: can still be reproduced if first paladin uses retribution aura and removes it.
