### ISSUE TITLE
[Deathknight] Death and Decay - Missing Threat modifier

### ISSUE THREAD

**Issue by burkey6** [dalaranwow/dalaran-wow#2618]
Death and Decay 's Extra threat modifier is broken again.

For the one day it worked we were looking at actually having a Deathknight main tank as they would be able to hold threat on more than 2 targets.

As of now it only generates 6-7k threat over its full duration

While it was working or atleast close to perfect it was generating 20-30k threat over its full duration.

To be honest this should be considered a priority fix as this is almost completely preventing the class from performing its tanking role.

**Comment by ntt1** [comment]
Quoting the guy who made a very on-point research and is absolutely right that the 1.9x threat per point of damage is missing on death and decay (which gets multiplied by additional 2x when in frost pressence):

"
Death and Decay http://wotlk.openwow.com/spell=49938
The Text tells: This ability produces a high amount of threat.
According to wowpedia (http://wow.gamepedia.com/Threat) this threat factor should be 1.9x when in frost presence.
With Frost Presence http://wotlk.openwow.com/spell=48263 activated the DK cause 2x threat. So the combined threat caused by Death and Decay should be 3.8x damage. (both factors stack multiplicatively as described on the wowpedia website)
A guildmate of me will post screenshots that proof that the current threat caused is only the 2x from the frost presence and the 1.9x factor is missing.

This bug has huge impact on DK group tanking: DKs dont have aoe taunts, and relying heavily on DnD threat. The other options (for blood DK tank): blood boil, that causes no extra threat and has kinda low damage, and spreading plagues, those need at least 3 abilities ( for both plagues spreaded) and the caused threat and damage is kinda low too at first (DoT). In addition to this flawed alternatives dnd costs 3 runes!

With the extra threat that is promised in the description DnD still isnt a fire-and-forget weapon in threat realm but it can rightfully claim the place as most important group tanking ability of dks which compensates for non-existent group taunt other tanks have.
Right now its lost runes for tank dks, because threatwise now the only viable solution is to single-focus one after another and pray that the keyboards of the dps' have fallen down simultanously when you as tank engaged.
"
And yes, crucial bug.

**Comment by Lothloryen** [comment]
This was corrected already, if anyone can confirm that it still happens, comment below, please.

**Comment by Oggilito** [comment]
Still experiencing this problem. DnD is generating around 6k threat over its full duration

**Comment by TeridanDW** [comment]
From ptr, the 1.9x threat mod is missing, as mentioned above:
 - Without frost presence
![image](https://cloud.githubusercontent.com/assets/6797611/25894728/abf0e156-3585-11e7-8dff-4c942534f71b.png)

 - With frost presence:
![image](https://cloud.githubusercontent.com/assets/6797611/25894770/df5d7fa4-3585-11e7-9420-ea808ada43fb.png)

**Comment by Rushor** [comment]
the spell which needs the threataddition https://wowgaming.altervista.org/aowow/?spell=52212

**Comment by Rushor** [comment]
DB/Spell: Frost Presence - Add linked spell Tank Class Passive Threat (57340) + Add 1,9 threat modifier for Death and Decay (52212)

* closes: https://github.com/dalaranwow/dalaran-wow/issues/2618
* commit: f822d5eadddeba184fc52653da3de5c60aa0d188

The issue has been fixed by a developer and will be tested on the Public Test Realm in the future (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm in the future.
This means that the issue exists in game at the moment i wrote this message.
**Only once the issue was marked with "Fixed - On Live Server", you can find the fix on your game server.**
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Byssarod** [comment]
Still not on Live Server after 3 months. Its only spell for AoE threat on DKs. Can we expect this fix on live soon?

**Comment by TeridanDW** [comment]
Works as intended in both cases pointed above on PTR.
