### ISSUE TITLE
 [Quest] Revenge for the Vargul

### ISSUE THREAD

**Issue by Snusnufs** [dalaranwow/dalaran-wow#2628]
You start the quest and the first champion attacks you http://wotlk.openwow.com/npc=30483, you kill him and then noting. The next mob that should attack you http://wotlk.openwow.com/npc=30484 doesn't do anything. She is "red" but non-attackable.
![mob1](https://cloud.githubusercontent.com/assets/13010665/8610761/f168b86a-26b6-11e5-9bba-ad383f65cd09.jpg)

**Comment by Drovana** [comment]
stand close to brita when you kill volgur to make it work
and ofc stand close to the thane when you kill brita ;)

**Comment by sianios** [comment]
Drovana solution confirmed, I managed to complete the quest

**Comment by ImprezaWoW** [comment]
When trying it today, seems like Volgur attacks you after placing the sword down and resets after the first hit you make, making neither him or Brita and Thane attackable.

**Comment by Golganeth** [comment]
Yes, the event may get stuck. Workaround still works

**Comment by MrAndersonX** [comment]
Yep still bugged. Workaround works.

**Comment by Rushor** [comment]
i'm going to fix this today @MrAndersonX

**Comment by Rushor** [comment]
if the creatures is not in your visibility range, the event will stuck

**Comment by MrAndersonX** [comment]
Thank you @Rushor :P !

**Comment by Rushor** [comment]
hm more specific: she will reset because the combat distance is too low

**Comment by Rushor** [comment]
DB/Quest: Revenge for the Vargul - Increase combatdistance to 200 yards and set the creatures active

* with this addition they will not reset in the room, if you killed the previous victim too far away from the next victim (Volgur > Brita > Thane Illskar)
* closes https://github.com/dalaranwow/dalaran-wow/issues/2628
* commit: a41a1a73a5b8c348d0562f19b87b5e770d9f1e50

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Hello on PTR I was able to reproduce:

>  - with this addition they will not reset in the room, if you killed the previous victim too far away from the next victim (Volgur > Brita > Thane Illskar)

so even though they are active the issue remains.
