### ISSUE TITLE
[PvP] Combat and vehicles

### ISSUE THREAD

**Issue by buugss** [dalaranwow/dalaran-wow#2652]
When you get into combat with a vehicle, you cannot leave combat until you die or the vehicle dies, or use feign death etc.
Combat with vehicles should work the same way as combat with players.

**Comment by Rushor** [comment]
Game/Entities: CanHaveThreatList - Ignore Threatlist only for Vehicles with PvP-Flag

* closes https://github.com/dalaranwow/dalaran-wow/issues/2652
* if you kill a vehicle in pvpfight (f.ex in sota) you will no longer get the combatbug, because the vehicle itself will no longer have a ThreatList
* commit: db22970b1afc2f5b5ab4f04f77eed4facfa4da9e

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Aridam** [comment]
Still an issue -- getting in Combat with any sort of Vehicle entity gets you stuck until the one operating it leaves it, it gets destroyed, or you die.

**Comment by Aridam** [comment]
Bump.

Over a year. Still an issue like in WG with unmanned Wintergrasp Tower Cannons even.
