### ISSUE TITLE
[Quest] The Fel and the Furious

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#267]
Quest The Fel and the Furious - 10612/10613

Issue: The event and the quest itself doesn't work. You are unable to interact with the game object "Fel Reaver Control Console" -185057.
Once you take over the control, you should be able to interact with the "Robotic Creature" which has ability to shoot rocket missiles on the nearby Deathforged Infernals.
You also have 5 minutes to do this quest. (which already works)

There is also a lot of missing Deathforged Infernals all over the place, you'll only see them in the first section / zone of the quest, once you go up the stairs there are no more, which also makes this quest impossible because player won't have enough NPCs to destroy.
How the quest has to work: 
http://www.youtube.com/watch?v=syz9M2pgvN8

http://wotlk.openwow.com/object=185057
http://wotlk.openwow.com/quest=10612
http://wotlk.openwow.com/quest=10613

**Comment by martijnhaah** [comment]
Confirmed that the control does not work, however, infernals are spawned enough.

**Comment by Klala** [comment]
The Fel Reaver Control Console on horde side doesn't even exist. Just noting it in case you missed it.

**Comment by Demlock** [comment]
Confirmed. The control consoles are not where they should be on the Horde side.

**Comment by catta000** [comment]
Quest still not working - on alliance side unable to interact with the "fel reaver control console"

**Comment by Cone182** [comment]
Confirmed. Needs to be fixed

**Comment by Finlaypro** [comment]
11/10/2015: Still not working.

The control consoles are not where they should be on the Horde side.

**Comment by DrFuler** [comment]
03/01/2016: Still not working.

The controls on the Horde's side doesn't even exist.

**Comment by Rushor** [comment]
f7876e2e9d78972dbf896c7d2aea054e45e8058d
54be84a2ab4efbd79221fda57dde9bc4fd73a336

**Comment by Rushor** [comment]
f2edb1cb550746aad6b86abdbce67dc9a9e596f4
- you can now controle the vehicles and get the cillcredits. there are some problems with the vehiclespells (no cooldowndisplay etc.) but these are all general problems with all vehicle

**Comment by Golganeth** [comment]
Copypaste
>Quest is completable by spamming http://www.wowhead.com/spell=38055/destroy-deathforged-infernal and running around easily. However the spell has a 5 second cooldown, as opposed to 10 seconds on retail (see https://youtu.be/_4YAH4_MEvU?t=53s). The cooldown also does not show on the action bar. This counts for all the abilities.
Visual also missing for the ability 38055.
Abilities http://www.wowhead.com/spell=38052/sonic-boom and http://www.wowhead.com/spell=38006/world-breaker have no cooldown altogether, making them easily spamable because they do not trigger GCD.
Sonic Boom should have a 15 second Cooldown, World Breaker a 10 second cooldown. As seen in the same video above, in a timeframe of ~15 seconds of when it starts.
Some mobs seem to evade bug (only confirmed http://www.wowhead.com/npc=21754/shadow-council-zealot), but will still follow the Fel Reaver.

**Comment by Rushor** [comment]
Game/Spells: Add/Increase GCD/CD for abilities of the reavers for quest: The Fel and the Furious

* closes https://github.com/dalaranwow/dalaran-wow/issues/267
* commit: 170c0f8025acbba1050515999bc88fb134a13239
* Spell: Destroy Deathforged Infernal = 10 seconds cd now
* spell: Sonic - Boom = 15 seconds cd now
* spell: Worldbreaker = 10 seconds cd now

The issue with the missing visual effects and the missing display of the cooldown is a gernal problem with most vehicles. please open a new issue for this (you can include the example from this quest) in the new issue.

The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
This still an issue on ptr:

> The issue with the missing visual effects and the missing display of the cooldown is a gernal problem with most vehicles. please open a new issue for this (you can include the example from this quest) in the new issue.
for these Fel Reavers and would like to add 1 more:
 - if all 3 reavers are taken by players or are dead and player clicks on object 185057 or 185034 or 185058 he will still get the buff http://wotlk.openwow.com/spell=38121 and the timer even though he is not controlling one.
![image](https://cloud.githubusercontent.com/assets/6797611/24698468/744bff8a-19f9-11e7-8227-10b48f1e3e12.png)

But this is just visual issue so opening and marking as:
