### ISSUE TITLE
[GO] Edge of Madness - Zul'Gurub

### ISSUE THREAD

**Issue by Torrigan** [dalaranwow/dalaran-wow#2761]
Was attempting to get my trinket from doing the Edge of Madness, farmed all the materials for the Mojo to extinguish the brazier and when I came to do it, I found that the brazier is not there to extinguish.

**Comment by notzuja** [comment]
The brazier was there before the last major bugfixing patch, but it seems to have been removed. However, even when it was there, it did nothing, so yeah.

**Comment by Rushor** [comment]
Scripts/Zul'Gurub: Implement: The Edge of Madness

* after using the gameobject, one of the four creature: Hazza'rah(15083), Wushoolay(15085), Renataki(15084), Gri'lek(15082) will spawn
* closes https://github.com/dalaranwow/dalaran-wow/issues/2761
* commit: f6526db58af08607b8be08c4b0f66a7a3ede0a89

![GitHub Logo](http://i.imgur.com/WCp7Wd8.jpg)
![GitHub Logo](http://i.imgur.com/dcOEGuH.jpg)
![GitHub Logo](http://i.imgur.com/MCxHaAq.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment]
Reference: https://github.com/dalaranwow/dalaran-wow/issues/4124

**Comment by Torrigan** [comment]
Is there an ETA on when this will be implemented? I just went in to see if it had and the brazier still did not spawn.

**Comment by Edzero** [comment]
Issues must be applied to the PTR for testing before they can then be applied to the live realm. The labels on the issue will change as it progresses through the stages.

**Comment by Torrigan** [comment]
The brazier still does not spawn on the live server even after the recent update, so this is still an issue.

**Comment by Edzero** [comment]
It has the "Fixed - Waiting for PTR Update" label on it, therefore it won't be on the live realm yet. The ICC update did not include all of the other fixes waiting on the bug tracker.
