### ISSUE TITLE
[Mage] Talent Burning Determination

### ISSUE THREAD

**Issue by Vaxsysl** [dalaranwow/dalaran-wow#3183]
Mage Talent "Burning Determination" has two bugs.
http://wotlk.openwow.com/spell=54748
http://wotlk.openwow.com/spell=54749

*1 Bug is that it is a magical buff, instead of physical. It can be dispelled, spellstolen - however, I am unable to find any proof other than openwow calcification, even though it kind of makes sense as it has nothing to do with our magical capabilities, but our mental aptitude. Therefore, unconfirmed.
*2 Bug (or glitch) is that one's own Arcane Torrent racial is triggering the talent. Image: http://imgur.com/X2ooAWu (check combat log)

**Comment by ashido96** [comment]
Very similar to how the paladin talent "reckoning" can also be triggered by arcane torrent.

**Comment by Rushor** [comment]
Game/Spells: Mage - Burning Determination - No longer proccs on passive effects (f.ex.: Arcane Torrent) and can no longer be dispelled 

* closes: https://github.com/dalaranwow/dalaran-wow/issues/3183
* commit: bd3ffa874ac645e73506efcfd9344f8a7c74fe04

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
After few fast tests on PTR the results are:

> - Burning Determination - No longer proccs on passive effects (f.ex.: Arcane Torrent) 

is still an issue.
![image](https://user-images.githubusercontent.com/6797611/31883357-4e49bf4c-b7f2-11e7-8781-f8b9b69ab8f4.png)

> and can no longer be dispelled

is fixed.
