### ISSUE TITLE
[Ulduar] Yogg-Saron Issues

### ISSUE THREAD

**Issue by saltylopez** [dalaranwow/dalaran-wow#3485]
From learning Yogg-Saron with my guild, I have observed several issues.  Yogg is already an encounter that requires excellent communication and coordination, so these bugs that I have observed can be crippling for a raid that is otherwise performing well.  They tend to inject a bit too much RNG to the encounter and many wipes occur due to bad luck (Though we wipe plenty from mistakes too).

- Phase 1 Cloud area. The clouds in phase 1 of the encounter seem to have a much larger radius that will cause them to trigger than they were on live.  At 35 seconds in the following video you can observe a tank ferrying a Guardian of Yogg-Saron through three clouds that he gets very close to.  On this server he would have triggered at least two of those clouds.

https://www.youtube.com/watch?v=0ZEJA52NrgI

I'm not sure if this is an issue of bounding, latency or perhaps something else.

- Loss of player control issues.  This bug is also referenced here: #3232 

This seems to be a general issue with encounters where players lose control of their character.  Sometimes it takes a few seconds after Mind control or Malady of the Mind has worn off before the player regains control of their character.  Last night, we had a lock lose control of his character for a solid 10-15 seconds after the debuff had worn off.  I've observed this in this encounter with Mind Control and Malady of the Mind and also in the Kel'Thuzad encounter with his Mind Control.

- Constrictor Tentacle hit points.  This may be intentional, but the Constrictor tentacles have double the hp values of their retail counterparts.  The Crusher and Corruptor tentacles are much closer to their retail values.  The doubled hit points is not insurmountable, but is still a considerable increase in difficulty when trying to free squeezed players.

http://wowwiki.wikia.com/wiki/Yogg-Saron_(tactics)

- Malady of the Mind.  Malady of the Mind still seems to be able to reach players after they take portals into the brain room.  This issue seems to have been referenced several times a year ago (example: #2498).  I'm aware that Malady can be carried into the portal room if a player clicks on a portal with the debuff, but I'm instead referring to a character getting the debuff while in the back of the room with no-one else previously affected in the portal room.

I believe that Malady may be chaining from outside the portal area to into the portal areas, perhaps caused by an unlimited z-axis?  Either that or Sara is targeting players after they've taken portals.

These issues take an encounter that is already tightly tuned and turn it into a frustrating RNG nightmare when trying to finish up attunements.  I think Yogg is a significant bottleneck for much of the server and it is certainly more difficult than any of the non-heroic encounters in Trials of the Crusader.  Thank you for your time and consideration in reviewing these matters.

**Comment by Thunderthigh** [comment]
As mentioned in the tank spot video here (https://www.youtube.com/watch?v=0ZEJA52NrgI&#t=285s) and later here (https://www.youtube.com/watch?v=0ZEJA52NrgI&#t=395s), Constrictor Tentacle's (npc=33983) Squeeze ability (spell=64126) should be cancelled by Ice Block, Hand of Protection, and Divine Shield. Currently, these abilities are preventing the physical damage of Squeeze, but are not cancelling the effect.

**Comment by Crispybuilt** [comment]
**I also want to add the issue for Phase 2**:
Portals spawn way too fast and it makes Phase 2 a complete joke.
Originally when Ulduar was released, Yogg was working great, but it was broken after some time.

**Comment by Lothloryen** [comment]
Hello there,

Thank you for the reports, really appreciated. Indeed, it seems few things got broken during the past months, quite sad to see no one has reported the portal/illusion issues until now - just checked it and it was a mere mistake from my side, which is already corrected.

I will take a look to the rest.

**Comment by saltylopez** [comment]
An additional bug related to Malady of the Mind:

Sometimes where a player looks to be pathing to one direction while under its effects, but will reappear in a different spot after the player regains control of their character.  This may be related to #1447

This bug is particularly nasty against Yogg because obviously players are moving away from where their clients show the afflicted character to be, but if the afflicted character is desynchronized and teleports to a different spot they could chain the Malady anyway.

**Comment by LoveDalaranWow** [comment]
Speaking of Yogg, the Insanity bug is still a thing: if a players goes insane for any reason and relogs fast enough, he becomes immune to Insanity mechanics, but is considered as a normal ally, with the increased damage and hp buff. A LOT of people exploied (and still do) this bug to get Yogg kills.

**Comment by ashido96** [comment]
Will chip in that paladin's Divine Shield works on 10 man, always just assumed it was a bug and weren't supposed to be able to do that to get out of the constrictor.

Other thing is that warlocks can cast their portal while they are constricted then teleport out of it.

**Comment by Lothloryen** [comment]
All the mentioned issues should be corrected after the next scheduled maintenance, except the problem when a player relogs while being with the Insane debuff which should be looked into during the next few days.

Thank you everyone.
