### ISSUE TITLE
[Quest][Northrend] Two Wrongs

### ISSUE THREAD

**Issue by Ergates82** [dalaranwow/dalaran-wow#3773]
**Description**:
The Northrend Alliance quest 'Two Wrongs', obtained from Mage-Lieutenant Malister at Westguard Keep, Howling Fjord, Northrend has two problematic issues that make it extremely difficult to complete. The player is provided with an item by this NPC in the form of a wand. The player must enter The Ember Clutch, Howling Fjord, Northrend and target a Proto-Drake that flies overhead, use the wand upon it which causes it to land and attack the player. Killing three Proto-Drakes completes the quest.
http://www.wowhead.com/quest=11188/two-wrongs

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
The Proto-Drakes are not visible when standing in the Ember Clutch, because either they fly too high, or the server's view distance is not set correctly. The only method of targeting one is to use a targeting macro. Once targeted and attacked with the wand, the Proto-Drakes behave in an erratic manner, sometimes flying down, attacking the player once with a wind buffet ability before flying off again, making them impossible to kill; sometimes landing and attacking the player.

**Expected behaviour**: Tell us what should happen instead
The Proto-Drakes should be visible flying above the Ember Clutch and selectable without using a targeting macro. Using the wand upon them should always cause them to fly down and attack the player until killed, the drakes should not fly off after using only one spell upon the player. 

This is an important quest because it is an opener for the entire Westguard Keep chain of quests. Unless completed, players will not be able to do any further quests in Westguard Keep.

**Steps to reproduce the problem**:
1. Obtain the quest 
2. Enter the Ember Clutch
3. Note that no Proto-Drakes are visible overhead
4. Use a targeting macro to select a Proto-Drake, such as '/targetexact Proto-Drake'
5. Wait for the drake to attack and observe it's behaviour

**Include proofs for this behaviour**

I'm sorry but I have no idea how to provide proof of this issue. Wowhead etc. only provide details of how the quest works correctly on retail servers, I can find no information online of this quest specific to Dalaran WoW.

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment]
DB/Quest: Two Wrongs - Improve combatbehaviour of Proto-Drakes

* closes https://github.com/dalaranwow/dalaran-wow/issues/3773
* the viewdistance cannot be changed by us, but the drake should no longer fly away after you used the item on him with this fix
* commit: bd4fba7f494ead943c52fa388908b30ce8c41f48

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Dancingirl** [comment]
This issue is still going on this day January 26th 2018 on Algalon.... More than a year after you said it would be fixed... Only the 1st one I targeted stayed and I was able to kill, the next ones I tried flied off after wing buffet

**Comment by JoPeAlmeida** [comment]
> This issue is still going on this day January 26th 2018 on Algalon.... More than a year after you said it would be fixed... Only the 1st one I targeted stayed and I was able to kill, the next ones I tried flied off after wing buffet

This issue is still not fixed. I can see the dragons, but their behaviour is still bugged
