### ISSUE TITLE
[Mage] Focus Magic and Arcane Potency stays after respec

### ISSUE THREAD

**Issue by plznoz** [dalaranwow/dalaran-wow#3910]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Currently you can keep Focus Magic and Arcane Potency when you respec away from arcane into a spec without those talents.

**Expected behaviour**: Tell us what should happen instead
Those buffs should be removed when you respec.

**Steps to reproduce the problem**:

1. Focus magic a player, and use Arcane Potency
2. Respec to a different spec without those talents
3. Check that you kept buff and your fm target kept his buff.

**Include proofs for this behaviour**
![http://i.imgur.com/l2kWnue.png](http://i.imgur.com/l2kWnue.png)
Focus magic and Arcane Potency stays active as seen on image (even though the spec doesn't have those talents).

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

http://wotlk.openwow.com/spell=57531 Arcane Potency
(http://wotlk.openwow.com/?search=arcane+potency)

http://wotlk.openwow.com/spell=54646 Focus Magic
(http://wotlk.openwow.com/?search=focus+magic)

**Comment by Rushor** [comment]
new feature (changespec) needed

**Comment by Rushor** [comment]
all spells (which are listed below) will now be recalculated/removed on player and group after specchange

```c++
enum BuffstackingSpells
{
    SPELL_LEADER_OF_THE_PACK = 24932,
    SPELL_RAMPAGE            = 29801,
    SPELL_OVERKILL           = 58427,
    SPELL_MASTER_OF_SUBTLETY = 31665,
    SPELL_TOTEM_OF_WRATH     = 63283,
    SPELL_ARCANE_POTENCY_1   = 57529,
    SPELL_ARCANE_POTENCY_2   = 57531,

    // Seals
    SPELL_SEAL_OF_VENGEANCE  = 31801,
    SPELL_SEAL_OF_CORRUPTION = 53736,
    SPELL_SEAL_OF_WISDOM     = 54940,
    SPELL_SEAL_OF_LIGHT      = 20165,
    SPELL_INNER_FIRE         = 588
};

static const uint32 blessings[]                         = { 19740, 20042, 25782, 19742, 20244, 25894 }; 
static const uint32 paladinAuras[]                      = { 465, 20138, 19746, 20254 }; 
static const uint32 seals[]                             = { 20187, 31801, 31803, 31804, 53733, 53736, 53742 }; 
static const uint32 warriorShouts[]                     = { 469, 1160, 6673 }; 
static const uint32 iDeffStance                         = 29594; 
static const uint32 iBerserkStance                      = 7381;
                                                        
static const uint32 hunter[]                            = { 13165,61846,13163,5118,13159,34074,34666,1130, 1494, 19878, 19879, 19880,19882, 19884 };
static const uint32 iVilePoisons                        = 32645;

static const uint32 iImprovedPowerwordFortitude         = 1243; 
static const uint32 iImprovedPowerwordFortutudeRaidbuff = 21562; 
static const uint32 iImprovedInnerFire                  = 588; 

static const uint32 shaman[]                            = { 324, 974, 52127, 51940, 8026, 974 };
static const uint32 warlock[]                           = { 18693, 30149, 706, 28176, 28189, 47892, 47893, 30147, 55151, 32795, 55195, 30147 };
```
Scripts/Custom: Add spellchecks for all specs in TalentSpecializationChange 

* closes https://github.com/dalaranwow/dalaran-wow/issues/3910
* commit: 09c49d49d4178adad2effd8db17adfdf546675ca

![GitHub Logo](http://i.imgur.com/6NL7SqD.jpg)
![GitHub Logo](http://i.imgur.com/SLLeybS.jpg)
![GitHub Logo](http://i.imgur.com/kF4TbZS.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by plznoz** [comment]
Didn't see Focus magic in that list. Was that fixed aswell?

**Comment by Rushor** [comment]
yes:

```c++
if (Group* group = player->GetGroup())
            {
                for (GroupReference* itr = group->GetFirstMember(); itr != NULL; itr = itr->next())
                    if (Player* member = itr->GetSource())
                    {
                        if (member->HasAura(54646, player->GetGUID())) // mage - focus magic
                            member->RemoveAurasDueToSpell(54646);
                        if (member->HasAura(54648, player->GetGUID())) // mage - focus magic
                            member->RemoveAurasDueToSpell(54648);
                    }
            }
```

more spells i didn't mentioned above:
48412, 48266, 48263,

**Comment by plznoz** [comment]
Alright, cheers.

**Comment by maciejpk** [comment]
Issue is still present (screenshots made in rhc, ahn'kahet kingdom)
![21st](https://user-images.githubusercontent.com/5055263/89161786-5d360c80-d573-11ea-8571-4f850a3a2e4b.jpg)
![22nd](https://user-images.githubusercontent.com/5055263/89161790-5e673980-d573-11ea-8bf5-d1dc9035d83d.jpg)
