### ISSUE TITLE
[Mechanics] While in group many dead NPCs which have no loot for you appear lootable

### ISSUE THREAD

**Issue by datbunneh** [dalaranwow/dalaran-wow#3944]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**:

While in group many dead NPCs which have no loot for you appear lootable

**Expected behaviour**: Tell us what should happen instead

The dead bodies should not appear lootable when there is no loot there

**Steps to reproduce the problem**:

1. Get into party or raid group and enter some instance
2. Move through the instance and every member of the group should be looting killed NPCs along as you go
3. Some NPCs that have nothing for you (probably ones been looted by other members) appear lootable (bag icon appear when you hover bodies and an empty loot windows is displayed when you click)

**Include proofs for this behaviour**

TBD

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

It's a generic issue that is reproducible in any instance (and probably outside) so it's not limited to any specific zones or objects

**Include Screenshots from the issue if necessary**

TBD

**Comment by Rushor** [comment]
fixed in https://github.com/TrinityCore/TrinityCore/pull/16265

**Comment by Rushor** [comment]
Game/Player: Update loot restrictions

commits:

- ac704437cf9164f6adb10876ee61105fc5014590 Game/Player: Update loot restrictions
- bf374b49b84753f12162128c7d438fba5f53a145 Game/Player: Update loot restrictions
- 99d3ffa16c57659b03939a6a13ba586f5ea02dc2 Creature/Loot: Do not display "lootable" sparkles for player even if others in the group still have quest items to be looted from creature.
- b255f731e12b0bf9681ba0ba650c264afdee88ea Looting/Group: Do not display looter in tooltip when FFA loot is enabled.

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by datbunneh** [comment]
Also would be cool to have this one live. ^.^

**Comment by datbunneh** [comment]
@Lothloryen Not sure, but it looks like fix for this issue was applied on live server.

**Comment by datbunneh** [comment]
Nevermind, not fixed.

**Comment by datbunneh** [comment]
@Lothloryen Not sure what the line "Sparkles will not be displayed for player even if others in the group still have quest items to be looted from creatures" in changelog was standing for but NPCs without anything to loot still appear lootable on live server. I've earlier noticed to be fixed in Naxxramas 10 for once, but everywhere else it's still bugged.

**Comment by Rushor** [comment]
continued in https://github.com/dalaranwow/dalaran-wow/issues/5367
