### ISSUE TITLE
[Hunter] Uncastable misdirection bug

### ISSUE THREAD

**Issue by KerDW** [dalaranwow/dalaran-wow#3999]
**Current behaviour:** 

Misdirection bugs when you click it too quick before the GCD (Global Cooldown) is over. Cannot be casted again until you die or relog, it stays "dark" as if it was casted on someone permanently but it is not casted on anyone.

**Expected behaviour:** 

Misdirection should just not bug like this, no matter how quick you press it it should work normally.

**Steps to reproduce the problem:** 

Cast a spell that uses a full GCD, e.g. Volley; before the GCD is over, cast Misdirection quickly in a party/raid friendly target. If you were quick enough, the reproduction rate for this bug is 100%.

**Include proofs for this behaviour:**

https://www.youtube.com/watch?v=q7CsEIunSoA
Video where I easily reproduce the bug, I was even kind of slow in this try. 

**Include the ID for the game objects, npcs (creatures, pets, minions), spells, items, quests, instances, zones, achievements, skills.**

http://wotlk.openwow.com/spell=34477

**Comment by Rushor** [comment]
https://github.com/dalaranwow/dalaran-wow/issues/1124

Visual sssues with that spell are blizzlike: see https://us.battle.net/forums/en/wow/topic/6036885168

anyway: fix for this can be found in https://github.com/Aokromes/TrinityCore/commit/cea753e4e615b130312daccae6f83488d284d396

**Comment by Rushor** [comment]
Game/Spells: Fixed spells like Shadowform, Tricks of the Trade, Misdirection getting stuck in unusable state clientside if they failed earlier because of GCD

* closes: https://github.com/dalaranwow/dalaran-wow/issues/3999
* commit: 2e0dbf0ef2411cf88f9d596259911f822332e6a8

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by tyler200100** [comment]
This is still happening very frequently with tricks of the trade. I was under the impression this would be fixed with the ICC release?

**Comment by TeridanDW** [comment]
Works as intended on PTR.

**Comment by TeridanDW** [comment]
Reopening is the fix was reverted and the issue is still present on live.

**Comment by ashido96** [comment]
Our guild has confirmed that tricks (haven't heard any complaints from our hunters) will bug if it is used during the global cooldown.

**Comment by Rahizm** [comment]
This is still happening with tricks of the trade.
