### ISSUE TITLE
[Quest][Northrend] No quest credit for throwing spears at Kraken

### ISSUE THREAD

**Issue by zykadelic** [dalaranwow/dalaran-wow#4246]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: The quest Get Kraken! from the Tournament grounds doesn't give credit for throwing spears at Kraken.

**Expected behaviour**: Throwing a spear at Kraken should give quest credit properly.

**Comment by Rushor** [comment]
http://wotlk.openwow.com/quest=14108

**Comment by Rushor** [comment]
DB/Quest: Get Kraken - Questcredit will now also be rewarded if player is on a vehicle, flying mount or taxi

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4246
* commit: 548e7bdf6d379979e8578b18746fb8349ab964de

![GitHub Logo](http://i.imgur.com/FNZPUOQ.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by zykadelic** [comment]
🙇

**Comment by Edzero** [comment]
In case anybody else is trying to do this quest:

It gives credit if you go on foot instead of using the hippogryph vehicle from the quest. Just target the mobs and use the flaming spears.

**Comment by thestranger064** [comment]
As of today 02/27-2020, you can only complete this quest on foot. 3 years later, still not implented.
