### ISSUE TITLE
[NPC][WotlK] Torseg the Exiled, missing emote

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4281]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**:  Torseg the Exiled http://wotlk.openwow.com/npc=29350 has 2 issues:
- He should be sleeping.
- He should be seen from far away. (Bigger distance than the normal creatures)

Thats him on the server now:
![wowscrnshot_012117_150809](https://cloud.githubusercontent.com/assets/6797611/22174619/7cc3b402-dfeb-11e6-97c7-4b8a8adcc849.jpg)

**Expected behaviour**: Video from retail legion from 21.01.2017:
https://www.youtube.com/watch?v=TZuq6K7C2Vs

**Comment by Rushor** [comment]
@Teridan-dal-wow : you killed the mammoths in front of him or to they also need the fake-death emote?

**Comment by Teridan-dal-wow** [comment]
Hello Rushor, no they are fine as they are now, on the video they were killed by players.

**Comment by Rushor** [comment]
alright tkanks

**Comment by Rushor** [comment]
DB/Creature: Torseg the Exiled - Set creature active + add sleep emotestate

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4281
* commit: 6b40003412f2dc8d6614e091fd4847b3fb002be5

![GitHub Logo](http://i.imgur.com/HAhlSK7.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Teridan-dal-wow** [comment]
Feedback for this report from TrinityCore rev. 02633a332cf7 2017-02-09.

> - He should be seen from far away.

The issue above is still present. I did some more testing on retail regarding the exact distance from which the player loses visuals of him (with the help of my water elemental and distance check addon) and came up with value of ~ 200 yards (not sure if the core supports this change now but for future reference is might help).

 - Regarding his sleep emote, found a small bug - if you engage the giant and he resets (you run away/die or gm on) he will run back to his possition stand still for 1-2 secs and instantly sleep (meaning the animation of him slowly laying on the ground is missing). Thats only when he reset, normal animation is working properly when you see him for first time (without engaging).

Everything else works exacly like retail. Thank you!

**Comment by Rushor** [comment]
the thing with the distance is only fixed on dalaan-wow, not on tc and the other thing is a generic bug that affects all creatures with such scripts
