### ISSUE TITLE
[NPC][WotlK] Hyldsmeet Warbear, missing mini event

### ISSUE THREAD

**Issue by TeridanDW** [dalaranwow/dalaran-wow#4309]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Npc Hyldsmeet Warbear http://wotlk.openwow.com/npc=30174 are friendly to players and to each other and do nothing.
![wowscrnshot_012417_162519](https://cloud.githubusercontent.com/assets/6797611/22250965/be291af0-e251-11e6-9674-353a63165b6c.jpg)

**Expected behaviour**: Hyldsmeet Warbear is suppose to:
 - Be hostile toward players (note: if player has http://wotlk.openwow.com/spell=55012 they should be friendly) if they haven't started the quest chain for the village.
Comment: If a player has http://wotlk.openwow.com/quest=12997 or http://wotlk.openwow.com/quest=13424 they should remain friendly until that player enters the ring and uses the reins http://wotlk.openwow.com/item=42499.
Proof: https://www.youtube.com/watch?v=9ob1xtAYXRw
 - Be hostile toward each other in all cases.
 - Stay around the ring, pulling a warbear too far away outside will cause them to reset. (Max range before they reset is ~50 yards)
![wowscrnshot_012417_164423](https://cloud.githubusercontent.com/assets/6797611/22251712/754ff206-e254-11e6-9d1e-d6065e81dc0b.jpg)
![wowscrnshot_012417_164238](https://cloud.githubusercontent.com/assets/6797611/22251720/7c3b5ccc-e254-11e6-8c16-ed79df3c927f.jpg)
 - Have very short aggro radius (check video below).
 - When Hyldsmeet Warbear dies should instantly spawn Hyldsmeet Bear Rider http://wotlk.openwow.com/npc=30175 (who is untargetable/unattackable(by all spells/effects including aoe) and he is also passive toward all npcs and players around him).
 - 5 secs after a Hyldsmeet Warbear dies it should despawn together with the rider it spawned.
 - Does not give any experience to players.
 - Does not give any loot to players.
 - Have AI so they can use all their skills (example: bash followed by charge followed by melee attack (couldn't find the exact spells they use) in a way that none of the spells are on cd and they can do the "combo" posted in example.

Video from retail legion from 24.01.2017:
https://www.youtube.com/watch?v=6RNysKeQPbs

Related issues : #3621 and #3930

**Comment by alexuktc** [comment]
Adding a problem with the player's bear - it cannot use the 2nd skill properly. It deals damage but no knockback. Interestingly enough the knockback works on all other npcs I could test it on - I went on to test on rhinos and revenants near the cave. They get knocked back.

**Comment by Rushor** [comment]
> Adding a problem with the player's bear - it cannot use the 2nd skill properly. 
was already fixed in https://github.com/dalaranwow/dalaran-wow/issues/3930

**Comment by Rushor** [comment]
Hmm all those issues were already fixed in https://github.com/dalaranwow/dalaran-wow/issues/3930 (knockback + increased damage)
and https://github.com/dalaranwow/dalaran-wow/issues/3621 (ai, vehicle linked despawn, aggro range, faction)

I will add a fix for the XP and loot then

**Comment by Rushor** [comment]
DB/Creature: Stom Peaks - Hyldsmeet Warbear - Increase Timer for AI abilities + Remove loot and XP

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4309
* commit: 5cbaa3e1fb3cee6b20d4c6d96b859895f61faab7
* commit: e69151f1e20fb1dc40de73471e251ccbf738a4d4

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Hello after few tests on PTR the results are:

 - Report #4309 and #3930 doesn't seems to be on PTR or not working at all as there is no change.

**Comment by Lothloryen** [comment]
@TeridanDW Test it now again, please. It should be on PTR.

**Comment by TeridanDW** [comment]
After a test on PTR this:

> DB/Creature: Stom Peaks - Hyldsmeet Warbear - Increase Timer for AI abilities + Remove loot and XP

Works as intended on PTR, with spell https://wowgaming.altervista.org/aowow/?spell=54460 been used extreamly rare (I saw it only once used against me), there might be issue with SAI.

But we still have this ingame:
![image](https://user-images.githubusercontent.com/6797611/32702092-eadf8c36-c7e9-11e7-847d-65bdc13a5d10.png)

meaning the actual mini event is missing (bear vs bear fights)
