### ISSUE TITLE
[Hunter][Spell] Chimera Shot - Serpent

### ISSUE THREAD

**Issue by plznoz** [dalaranwow/dalaran-wow#4575]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Chimera Shot - Serpent currently does way too much damage when a damage modifier is active.
I'm guessing it receives the damage modifier twice (for serpent sting and for chimera shot - serpent)

**Expected behaviour**: Tell us what should happen instead
Chimera Shot - Serpent should do 2x the dmg with a 100% modifier.

**Steps to reproduce the problem**:
1. Engage a boss with a dmg modifier as a hunter (for example Twins/beasts in Toc)
2. Check damage done with Chimera Shot - Serpent with and without the dmg modifiers.

**Include proofs for this behaviour**

**Twin Valkyrs Dalaran:**
http://www.worldoflogs.com/reports/y1ld98tjuh0o4hm0/log/?s=2169&e=2412
`[{"spellNames": ["Empowered Light"], "targetNames": ["Celfinnel"]}, {"spellNames": ["Chimera Shot - Serpent"], "eventTypes": [1], "sourceNames": ["Celfinnel"]}, {"spellNames": ["Light Essence"], "targetNames": ["Celfinnel"]}, {"spellNames": ["Dark Essence"], "targetNames": ["Celfinnel"]}, {"spellNames": ["Empowered Darkness"], "targetNames": ["Celfinnel"]}]`
![http://i.imgur.com/IkX3p8F.png](http://i.imgur.com/IkX3p8F.png)
Notice the damage is twice what it is on a normal boss with just a 50% modifier (see beasts below for normal dmg).
When the player gets empowered buff the damage becomes close to 5x what was with just the 50% modifier active.

**Twin Valkyrs LIVE (2010-01-28):**
http://www.worldoflogs.com/reports/dta08cx33i1g8unm/log/?s=4120&e=4309
`[{"spellNames": ["Empowered Light"], "targetNames": ["Sylvia"]}, {"spellNames": ["Chimera Shot - Serpent"], "eventTypes": [1], "sourceNames": ["Sylvia"]}, {"spellNames": ["Light Essence"], "targetNames": ["Sylvia"]}, {"spellNames": ["Dark Essence"], "targetNames": ["Sylvia"]}, {"spellNames": ["Empowered Darkness"], "targetNames": ["Sylvia"]}]`
![http://i.imgur.com/VUEYqDo.png](http://i.imgur.com/VUEYqDo.png)
Damage doubles with empowered buff, as one would expect.

**Northrend Beasts Dalaran:**
http://www.worldoflogs.com/reports/y1ld98tjuh0o4hm0/log/?s=23&e=426
`[{"spellNames": ["Chimera Shot - Serpent"], "sourceNames": ["Celfinnel"]}, {"spellNames": ["Staggered Daze"]}]`
![http://i.imgur.com/kZspKOp.png](http://i.imgur.com/kZspKOp.png)
Damage is 4x what it is normally.

**Northrend Beasts LIVE (2010-01-28):**
http://www.worldoflogs.com/reports/dta08cx33i1g8unm/log/?s=1766&e=2151
`[{"spellNames": ["Chimera Shot - Serpent"], "sourceNames": ["Sylvia"]}, {"spellNames": ["Staggered Daze"]}]`
![http://i.imgur.com/mqXwQer.png](http://i.imgur.com/mqXwQer.png)
Damage doubles with the 100% modifier, as one would expect.

http://www.worldoflogs.com/guilds/573/calendar/01-10/ To confirm live log is from live.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
http://wotlk.openwow.com/spell=53353

**Comment by plznoz** [comment]
Can add that Shadow Priests have a similar issue with Improved Devouring Plague.

Also worth checking if the spells get the 13% spell damage buff twice, and if they should (I don't know).

**Comment by Teridan-dal-wow** [comment]
Hello, there was an old bug where spell http://wotlk.openwow.com/spell=51735 used to stack incorrectly with simular effect in some situations, maybe its related to this report maybe its not.

**Comment by WhiteNigg** [comment]
confirmed, also seen it happen on my hunter with every damage multiplier. It used to be equally strong in ulduar during vezax with the  T8 2 set bonus and the effect of the pool, i would get 90k+ crits (in ulduar gear) while standing in it, unfortunately there are no logs of back then

**Comment by plznoz** [comment]
@WhiteNigg: Think vezax pool stacks twice on dalaran, thus the big damage. Probably not supposed to.

**Comment by Rushor** [comment]
Game/Spells: Hunter - Chimera Shot - Update damage calculation of Chimera Shot Serpent & Add 1 minute cooldown to Scorpid Sting

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4575
* commit: 6ece7fbda56d2adfae4cd071472a538d972d74df

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
I have done some tests on PTR for this issue in ToC 10 with
https://wowgaming.altervista.org/aowow/?spell=53353 and Staggered Daze 66758 and the extra damage bonus is still present.
This part of the spell:

> Serpent Sting - Instantly deals 40% of the damage done by your Serpent Sting.

seems to do too much damage when under the effect of dmg modifiers.

My stats:
![wowscrnshot_101317_173428](https://user-images.githubusercontent.com/6797611/31551792-4f988f6a-b03e-11e7-9a60-3ed6726141eb.jpg)

Damage without Staggered Daze
![wowscrnshot_101317_173812](https://user-images.githubusercontent.com/6797611/31551829-6bf23300-b03e-11e7-89cd-926ad0362462.jpg)

Damage with Staggered Daze
![wowscrnshot_101317_173618](https://user-images.githubusercontent.com/6797611/31551850-7f93f736-b03e-11e7-9883-fca36f39e8d4.jpg)

> Add 1 minute cooldown to Scorpid Sting

This part works as intended on ptr.

Reopening.

**Comment by robinsch** [comment]
Waiting for PTR Update.

**Comment by TeridanDW** [comment]
Works as intended on PTR.
![wowscrnshot_101617_110738](https://user-images.githubusercontent.com/6797611/31601441-8c0ce600-b262-11e7-9b13-b8fd1d2b7737.jpg)
![wowscrnshot_101617_110719](https://user-images.githubusercontent.com/6797611/31601442-8c290f38-b262-11e7-894f-b113a3a492aa.jpg)
