### ISSUE TITLE
[Black Temple] Illidan

### ISSUE THREAD

**Issue by alexuktc** [dalaranwow/dalaran-wow#4672]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Three issues occur which are problematic. 

1. If you DPS Illidan too fast in each phase he gets bugged out between phases and you cannot kill the boss.
2. Eye Beam visual is bugged, meaning it cannot be seen or dodged properly. And it can easily kill half the raid. 
3. If you wipe on Illidan the script making Akama fight the ever spawning Illidary Elite does not stop. They keep spawning and while Akama is fighting them you cannot click him again to start the event. 

**Expected behaviour**: Tell us what should happen instead
1. Illidan should be able to DPS-ed as fast as possible. Even to the point of ignoring mechanics because dps is too fast.
2. Eye Beam should be easily visible and dodgeable, as it can easily kill people, even on level 80.
3. The script should stop and Akama should be on top on the court of the Betrayer. You should be able to talk to him and redo the event as many times as you need to. 

**Steps to reproduce the problem**:

1. Try the fight.
2. Try the suggested mechanics.
3. Experience them without fail.

**Include proofs for this behaviour**
We are saved now and this is an issue. We cannot do it again until next week. However the issues can easily be reproduced if needed.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
npc=22917 - Illidan

**Include Screenshots from the issue if necessary**
My computer got way too laggy to be able to take a screenshot. There were probably thousands of Illidary Elite when I got there.

--------------

I made sure to check, no similar thread has been posted. This, along with the RoS issue which I have also documented in detail make BT a cancer to clear.

**Comment by ashido96** [comment]
Wow, can't believe I never made the bug report for this :( 
Confirming bug 2 and 3

**Comment by alexuktc** [comment]
In all fairness if issue no. 2 cannot be addressed people doing BT will be fine with having more than one attempt at Illidan per reset.

**Comment by ashido96** [comment]
@alexuktc Soft reset for raids is 30 minutes, if everyone leaves the instance for 30 minutes it should reset just like when raids used to get Hodir bug in ulduar

**Comment by alexuktc** [comment]
That is not true for BT. As I already said the script which forces Illidary Elite to keep spawning and attacking Akama simply does not stop. I went into BT a day later and there were thousands of mobs. Akama was not able to start the event as well.

**Comment by alexuktc** [comment]
Hello. 

I know that a label has been put on this, but is it possible to at least give an answer as to whether this will be considered soon at all?

**Comment by TeridanDW** [comment]
Hello, please do _**NOT**_ bump reports without providing a relevent, to the issue comment. It won't attact any additional attention to it nore it will be resolved faster.

 I will answer your question (as best as I can) this time only and _"never again"_ :roll_eyes: . All of the attention of the team is focused on the "events" that will happen on 27-th, there is a lot of work to be done so that everything goes as smootly as possible.

Regarding the Illidan issue - the encounter has been rewritten by a TC member here:
https://github.com/TrinityCore/TrinityCore/commit/8731975187694d1989af93f9569b591d4ebd767b
https://github.com/TrinityCore/TrinityCore/commit/50973e9d6fbf7537ae8d90535b9dfa25e5ce69f6
https://github.com/TrinityCore/TrinityCore/commit/bb3c964e7c0860d4448a065a2d1d37b52704da76

These commits needs to be tested on the ptr and if everything works as intended, applied on live. Currently it makes no sense fixing individual bugs in the outdated script (that live uses now).

I hope these 2 reasons/points answer your question.
Thank you.

**Comment by Rushor** [comment]
The issues were fixed from TC and will be applied on Dalaran-WoW with the next merges. A tester will recheck the fix first.

**Comment by alexuktc** [comment]
I am guessing you are testing fixes right now. We lost an ID because of it. 

Illidan used his Eye Beam 7-8 seconds into phase 2, catching us off guard. However, even after the elementals died he kept bugging out, jumping all over the place and casting AoE spells on the remaining people. He did not enter phase 3 and just killed us while being untargetable.

**Comment by alexuktc** [comment]
Update on this. Today Illidan did not use the Eye Beam in quite some time. The other skills worked fine, he was throwing AoE at people and using the focus DoT on  raid members. However the 2 crucial issues remain.

1. He did not enter Phase 3 after elementals died. Just stayed untargetable while spamming shit.
2. If you wipe/reset on the fight you lose the ID. as Akama cannot start the event again. 

In case of 2, Akama has to go up the stairs to his platform (next to the left stairs) and you should be able to start the event from there.
