### ISSUE TITLE
[Quest][Northrend] Fresh Remounts

### ISSUE THREAD

**Issue by Muncic** [dalaranwow/dalaran-wow#637]
http://www.wowhead.com/quest=12214

THe Mounts attack on their own and charge the enemy targets, you can't move him or run as you want if you are in combat ... they just keep charging and charging away... my blood boiled while doing this quest ... and when you bring the mount to the camp ... you can press the keybind to turn in the mount 3 times ... so you turn in the horse 3 times over

**Comment by ashido96** [comment]
For people that come to the bug tracker to check on info for bugged quests.
Tip: mount the horse that travels up and down the ramp to the beach from the main area and you can get to Venomspite without agroing anything.

**Comment by Vaxsysl** [comment]
What the upper comment said, get the a horse that's riding near the edge, and clear all enemies before that. If you get into combat with anyone, the horse won't be going anywhere, unless one of your friends can kill the mob (at least I think so, haven't tired with someone else killing the mobs I come into contact with).

**Comment by NovaHiros** [comment]
I've been trying to do this for hours. It's very irritating if you're fresh and alone. Just put this auto-complete for the sake of players, please...

**Comment by rinleezwins** [comment]
Well, at least you can complete the quest with just one horse by spamming the "hand over" ability, so there is that.

**Comment by Golganeth** [comment]
The part where you mount the horse and go back to the NPC to hand the reins over works great now. The horse will not go crazy, the NPCs attack you and you can normally walk back.

However, before to using the dropped quest item, horses are friendly to players even though they shouldn't. They should attack the player together with the rider. Once you use the quest item they should turn friendly.

Right now the horses wander around while the riders will try to attack you if you are at melee range.

**Comment by budthechud** [comment]
Currently having a partially related issue.  The horses are spawning without riders so I ma unable to gather reigns.  I have only found one knight on a horse and he was evade-bugged.  
No horses are able to be targeted or have knights.

**Comment by ImprezaWoW** [comment]
Currently the horses can not be targeted. Quest can not be done at all.

**Comment by GeneralSaurfang** [comment]
Currently, some of the horses have no knight riding on them, and are also not target-able.
The rest of them that have knights riding them, but all the knights I have seen evade every attack and avoid combat.
Checked every single knight in the vicinity marked by the game for this quest.

Completing the quest is currently impossible.

**Comment by MrAndersonX** [comment]
Like GeneralSaurfang said. It's still bugged in the exact same way.

**Comment by Rushor** [comment]
DB/Quest: Fixup "Fresh Remounts"

* closes https://github.com/dalaranwow/dalaran-wow/issues/637
* you can now easily kill the humans, get the item, charm the horses, run to the questgiver
* also the little cutscene where the horse get washed by acid was added
* commit: 06afab9853be97e87f79351cb61204c0fa8765ac

![GitHub Logo](http://i.imgur.com/SEjwchs.jpg)
![GitHub Logo](http://i.imgur.com/3dVglHK.jpg)
![GitHub Logo](http://i.imgur.com/OFrharl.jpg)
![GitHub Logo](http://i.imgur.com/uKBDVGe.jpg)
![GitHub Logo](http://i.imgur.com/zNKkJoQ.jpg)
![GitHub Logo](http://i.imgur.com/Yd58wJd.jpg)

The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by MrAndersonX** [comment]
Thank you mate !

**Comment by AshManson** [comment]
This quest is still bugged and I can't complete it.  Just a few days ago the knights were evading every attack as stated previously.  Now I can attack the knights, kill them, get the quest item, but the horses are now untargetable and thus unmountable.

**Comment by Rushor** [comment]
pls read what i wrote above before posting.

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Feedback for this issue:
 - horse still engage in combat nearby enemies (probably this fix is not on ptr)
 - when player use spell http://wotlk.openwow.com/spell=48297 he is ejected from the hourse (at that moment the hourse should gain reach- passive and  flags 768 as someone can attack him and brake the mini event

**Comment by Lothloryen** [comment]
On PTR.

**Comment by TeridanDW** [comment]
Hell after few tests on PTR for this issue the results are:

> horse still engage in combat nearby enemies.

is still an issue.

> when player use spell http://wotlk.openwow.com/spell=48297 he is ejected from the horse (at that moment the hourse should gain reach- passive and flags 768 as someone can attack him and brake the mini event).

is still an issue.

I also notice that when the player is mounted on the horse, he (horse) randomly change his speed (walking/running), but that's probably caused by issue 1.

**Comment by Aridam** [comment]
Just did the Quest, so it's doable.

Some Knights indeed Evade -- no just but to kill the Horse itself, then the Knight, and look for another pair.

Didn't notice any Knight-less Horses -- maybe just my luck in that regard (also it might be that some people kill just the Knights and leave the Horses like that for some odd, random reason).

Horses don't attack with the Knights that aren't actually stuck in Evade -- they just keep going on their waypoints so you have to keep following while killing the Knights off them. Same applies to when you get on them yourself -- ongoing waypoint needs to finish before you can actually move them yourself.

They don't seem to engage with nearby enemies on their own -- least for me that wasn't the case, as I was in full control.

Also, an abusable bug -- they don't despawn or anything like that after handing them in; you can literally just get one Horse and spam that, then dismount it -- it goes astray for a few seconds and then despawns on its own.
